#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JogoDaVelhaNicolasViana.Resource", IsApplication=true)]

namespace JogoDaVelhaNicolasViana
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tatooine = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int dialogue = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int eight = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int five = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int four = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int new_game = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int nine = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int one = 2131230722;
			
			// aapt resource value: 0x7f08000e
			public const int pontuacao = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int seven = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int six = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int tableLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int tableRow1 = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int tableRow2 = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int tableRow3 = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int three = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int two = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int OptionsMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int luke = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int vader = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int new_game = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int TelaCheia = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
